config/routes.rb
StarterSite::Application.routes.draw do
  resources :users
  resources :user_sessions
  resources :pages

match 'login' => "user_sessions#new", :as => :login
match 'logout' => "user_sessions#destroy", :as =>:logout
match 'signup' => "users#new", :as => :signup
match 'dreamweaver1' => "pages#dreamweaver1", :as => :signup

  root :to => 'pages#dreamweaver1'

end

app/models/page.rb
class Page < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation

    acts_as_authentic do |c|
    	c.login_field = :email
	end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base



end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
   protect_from_forgery

   helper_method :current_user_session, :current_user 

     protected

     private
   def current_user_session
    logger.debug "ApplicationController::current_user_session"
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
   end

   def current_user
    logger.debug "ApplicationController::current_user"
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
   end


   def require_user
    logger.debug "ApplicationController::require_user"
    unless current_user
      flash[:notice] = "You must be logged in to access this page"
      redirect_to :login 
      return false
    end
   end

   def require_no_user
    logger.debug "ApplicationController::require_no_user"
    if current_user
      store_location
      flash[:notice] = "You must be logged out to access this page"
      redirect_to '/support'
      return false
    end
   end

   def store_location
    session[:return_to] = request.request_uri
   end

   def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
   end

 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dreamweaver1
    @users = User.all

    respond_to do |format|
      format.html 
      format.json { render json: @user }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
end

app/controllers/user_sessions_controller.rb
 class UserSessionsController < ApplicationController
   before_filter :require_user, :only => :destroy

   # GET /user_sessions/new
   # GET /user_sessions/new.json
   def new
     @user_session = UserSession.new

     respond_to do |format|
       format.html # new.html.erb
       format.json { render json: @user_session }
     end
   end

   # POST /user_sessions
   # POST /user_sessions.json
   def create
     @user_session = UserSession.new(params[:user_session])

     respond_to do |format|
       if @user_session.save
         format.html { redirect_to users_path, notice: 'Login Successful - Welcome!' }
         format.json { render json: @user_session, status: :created, location: @user_session }
       else
         format.html { render action: "new" }
         format.json { render json: @user_session.errors, status: :unprocessable_entity }
       end
     end
   end

   # DELETE /user_sessions/1
   # DELETE /user_sessions/1.json
   def destroy
     @user_session = UserSession.find(params[:id])
     @user_session.destroy

     respond_to do |format|
       format.html { redirect_to :login }
       format.json { head :no_content }
     end
   end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def markdown
 	 markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
	 :autolink => true, :space_after_headers => true, :hard_wrap => true)
 end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html class="index">
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Dreamweaver Level 1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
</head>
<body>
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  <header>

  </header>
  <section class="main wrapper clearfix" role="main">
  	<%= yield %>
  </section> <!-- end main -->
  <footer>

  </footer>


  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>

  <script src="js/plugins.js"></script>
  <script src="js/script.js"></script>

  <script>
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>

app/views/pages/dreamweaver1.html.erb
<div class="content">
		<h1> Welcome to Dreamweaver Level 1 </h1>
     <h6> 
      It was a great 1st day of class. I want to thank you all for participating and being involved. Please study the class notes for day one
      and be prepared for a small quiz and "do it yourself" challenges next 
      Saturday. Also I can't emphasize this enough... practice, practice, practice.
      </h6>

      <h6> If you had to leave early or didn't attend class please download 
       <%= link_to "Download Day 1 Files", "https://s3.amazonaws.com/ra_epcc/dreamweaver1/Day+One+Files.zip", 
                 :target => "_blank" %> take a look at first_site, study the HTML and CSS and try to make your own version of the file. 


      <h6> Below you will be able to find resources that will be posted through out the course. Have fun!</h6> 
      <p> Day One </p>

      <ul>
        <li> <%= link_to "Download the Sylybus", asset_path('https://s3.amazonaws.com/ra_epcc/dreamweaver1/Syllabus.pdf'), 
        :target => "_blank" %>
        </li>

        <li> <%= link_to "Download 1st Day Class Notes", "https://s3.amazonaws.com/ra_epcc/dreamweaver1/day_one_notes.pdf", 
        :target => "_blank" %>
        </li>

        <li> <%= link_to "Download Dreamweaver Trail", "http://www.adobe.com/cfusion/tdrc/index.cfm?product=dreamweaver&loc=en_us", 
        :target => "_blank" %>
        </li>

        <li> <%= link_to "Download Day 1 Files", "https://s3.amazonaws.com/ra_epcc/dreamweaver1/Day+One+Files.zip", 
        :target => "_blank" %>
        </li>
      </ul>


          <p> Day Two </p>

          <ul>

          </ul>
</div>

app/views/user_sessions/new.html.erb
 <%= form_for(@user_session) do |f| %>
     <% if @user_session.errors.any? %>
       <div id="" class="notification_error">
        <h2>Check the following <%=pluralize(@user_session.errors.count, "error") %> </h2>

         <ul>
         <% @user_session.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
         </ul>
       </div>
     <% end %>

     <div class="field">
       <%= f.label :email %><br />
       <%= f.text_field :email %>
     </div>

     <div class="field">
       <%= f.label :password %><br />
       <%= f.password_field :password %>
     </div>

     <div class="actions">
       <%= f.submit 'Login' %>
     </div>

    <% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

    <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>